### ISSUE TITLE
Linux issue 

### ISSUE THREAD

**Issue by AlexeyIS** [kshoji/Unity-MIDI-Plugin-supports#16]
Thank you for the plugin. I have one issue when I try to build my app for the Linux, for some strange reason the plugin .so file not copied to the build folder. 
One strange line I've seems in Player log file
Fallback handler could not load library LinuxApp_Data/MonoBleedingEdge/x86_64/MIDIPlugin
Unity version 2022.3.13f.
Target is Linux with mono. 
Have you seen this before?

**Comment by kshoji** [comment]
Thanks for reporting the issue.

I checked this problem and found the cause.
The meta file was corrupted for some reason, so the plugin file wasn't included in the app's binary.

After finding and deleting the following files, try building the project.
```
Assets/MIDI/Plugins/Linux/MIDIPlugin.so.meta
```

This issue will be fixed in the next version.

**Comment by AlexeyIS** [comment]
@kshoji That fixed the issue! Thank you for the quick response!
